### ISSUE TITLE
Condense commands

### ISSUE THREAD

**Issue by MiGraber** [ptl93/AEDA#27]
At the moment we need multiple commands to produce one finished rmd file:
```
my.report.task = makeReportTask(id = "test.report", data = airquality, target = "Wind")
basic.report = makeBasicReport(my.report.task, data = airquality)
```
Here there are two commands
```
my.creport.task = makeCorrTask(id = "corr.report", data = airquality)
my.creport = makeCorr(my.creport.task)
corr.report = makeCorrReport(my.creport, type = "CorrPlot")
```
And here are 3 commands needed.
Should we condense it so we always need one? Or does this has low priority?

**Comment by tuanle618** [comment]
This might indeed be a user-friendlieness-feature. I suggest we just need one, because otherwise in the end there are too many function calls.

**Comment by tuanle618** [comment]
@MiGraber @daryabusen, I am currently working on extra feature makeCluster. I want to go that way that the `clusterAnalyis Obj` will be handed to `makeReport`-generic function. Could someone rewrite the current make*Report-function to one S3-Method ? Such that pipeline is the following: 

`data("Boston", package = "MASS")`

`basic.report.task = makeReportTask(id = "BostonTask", data = Boston, target = "medv")`
`basic.report = makeReport(basic.report.task, data = Boston)`

`num.sum.task = makeNumSumTask(id = "BostonTask", data = Boston, target = "medv")`
`num.sum = makeNumSum(num.sum.task)`
`num.sum.report = makeReport(num.sum)`

`corr.task = makeCorrTask(id = "BostonTask", data = Boston)`
`my.corr = makeCorr(corr.task)`
`corr.report = makeReport(my.corr, type = "CorrPlot")`

`cat.sum.task = makeCatSumTask(id = "BostonTask", data = Boston, target = "medv")`
`cat.sum = makeCatSum(cat.sum.task)`
`cat.sum.report = makeReport(cat.sum)`

`#combine all reports`
`finishReport(basic.report, num.sum.report, corr.report, cat.sum.report)`

**Comment by tuanle618** [comment]
Almost finished `makeClusterAnalysis()` .
I'll change the `make*Report()` function today into S3-Method: `makeReport()`

**Comment by tuanle618** [comment]
@MiGraber  
In `makeCorrReport` there is the additional argument "type".
Currently the code for this function only provides one choice of type.
Since I want to change the functionalities of all `make*Report` functions into one `makeReport` I wonder if it's able to change the "type" - possibility in either `makeCorrTask` where the user either defines the type or we take a default. Such that in `make*Corr*Report` the type can be selected from the `corrObj` itself..

Pls make sure that when adding possible function args, there are more possibilites than only the default method.

In the end we want to have something like this:
`corr.report = makeReport(corrObj)`
`num.sum.report = makeReport(num.sum.obj)`
`cat.sum.report = makeReport(cat.sum.obj`
....

**Comment by MiGraber** [comment]
I wanted to provide at least one other type, but I forgot about that. I will add a default. The type has no entry in the task because it should determine the type of plots which both (or at least the two I had in mind) can be plotted with the same data. And I should add correct arg checking.

**Comment by tuanle618** [comment]
So there is no option to call `makeReport(corrObj)` **without** `type` ?
Should be fine as well, I just thought if its possible to let the user decide it directly in makeCorrTask it'd be best, such that function calls for `makeReport` are always the same. You just input another analysis.object

**Comment by MiGraber** [comment]
> So there is no option to call makeReport(corrObj) without type ?

Sure: Defaulting type to "CorrPlot" should work.
--> `makeCorrReport = function(corr.obj, type = "CorrPlot")`
Or do you mean that the function should not have a second argument?
Even then we can include type in make*Task but then the same calculation may be made twice.

**Comment by tuanle618** [comment]
Yes I meant that the function only takes a `corr.obj` as input. I'd suggest going the "makeCorrTask" way. So all function calls for `makeReport` are the same (I am currently rewriting the function to an S3-`makeReport` function). I dont believe calculations will be made twice, since in CorrTask we just have the information? We can pass the `type `through the `makeReport `function and then in `CorrObj.makeReport` select the plot type according to the type. This way works if we save the task through all steps. (I did it with all my other functions).

**Comment by tuanle618** [comment]
finished PR #35
