### ISSUE TITLE
factor and ordered

### ISSUE THREAD

**Issue by MiGraber** [ptl93/AEDA#4]
https://github.com/ptl93/AEDA/blob/9e66cfdccdc088c157b2d6c4bdafc57d3e6762b3/R/getDataType.R#L40
Why aren't you seperate the check for ordered and factor variables?

**Comment by tuanle618** [comment]
@MiGraber  Because I researched on the internet and mostly when variables are supposed to be ordered, they are both "factor" and "ordered". Applying class(myvariable) came to the solutions "factored" , "ordered". When checking for single condition in the end both classes would be added. Maybe this can be solved with an exlusive XOR or another expression checking. But for now I let it like that

**Comment by tuanle618** [comment]
@MiGraber  I fixed this issue. If you have time, please have a look into the new version.

**Comment by MiGraber** [comment]
This probably works but if we are just interested that a var has the class ordered (not that it has both classes  ordered and factor) then we could do the same "trick" as for the integers, right? First check for ordered the check for factors.
